openapi: 3.1.0
info:
  title: Rimac Appointments API
  version: 1.0.0
servers:
  - url: https://msp8jya38d.execute-api.us-east-1.amazonaws.com
paths:
  /appointments:
    post:
      summary: Crea un agendamiento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAppointmentRequest'
            examples:
              pe:
                value: { insuredId: "12345", scheduleId: 901, countryISO: "PE" }
              cl:
                value: { insuredId: "67890", scheduleId: 902, countryISO: "CL" }
      responses:
        '200':
          description: Creado (pending)
          headers:
            Content-Type:
              schema: { type: string, example: application/json }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAppointmentResponse'
              examples:
                ok:
                  value: { appointmentId: "9ad5fee8-f646-481a-9693-916f21242edc", status: "pending" }
  /appointments/{insuredId}:
    get:
      summary: Lista agendamientos por asegurado
      parameters:
        - in: path
          name: insuredId
          required: true
          schema:
            type: string
            pattern: '^\d{5}$'
          example: "12345"
      responses:
        '200':
          description: Lista de citas
          headers:
            Content-Type:
              schema: { type: string, example: application/json }
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
              examples:
                sample:
                  value:
                    - appointmentId: "9ad5fee8-f646-481a-9693-916f21242edc"
                      insuredId: "12345"
                      scheduleId: 901
                      countryISO: "PE"
                      status: "completed"
                      createdAt: "2025-10-05T00:19:17.833Z"
                      updatedAt: "2025-10-05T00:19:18.340Z"
components:
  schemas:
    CreateAppointmentRequest:
      type: object
      required: [insuredId, scheduleId, countryISO]
      properties:
        insuredId:
          type: string
          description: ID del asegurado (5 dígitos)
          example: "12345"
        scheduleId:
          type: integer
          description: ID de la agenda/horario
          example: 901
        countryISO:
          type: string
          enum: [PE, CL]
          description: País de operación
          example: PE
    CreateAppointmentResponse:
      type: object
      properties:
        appointmentId: { type: string, format: uuid }
        status: { type: string, enum: [pending] }
    Appointment:
      type: object
      properties:
        appointmentId: { type: string, format: uuid }
        insuredId: { type: string }
        scheduleId: { type: integer }
        countryISO: { type: string, enum: [PE, CL] }
        status: { type: string, enum: [pending, completed] }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
